export default {
  SET_THEME_MODE: 'SET_THEME_MODE',
  LOGIN_SIGNUP: 'LOGIN_SIGNUP',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  SET_CITY: 'SET_CITY',
  RESET_CITY: 'RESET_CITY',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_STORIES: 'SET_STORIES',
  IS_LOCATION_SWITCHED: 'IS_LOCATION_SWITCHED',
  NOTIFICATION_UNREAD_COUNT: 'NOTIFICATION_UNREAD_COUNT',
  RESET_DATA: 'RESET_DATA',
};
