import {DefaultTheme} from '@react-navigation/native';

export const commonColors = {
  transparent: 'transparent',
  brandColor: 'rgba(91, 124, 253, 1)',
  brandColorLight: 'rgba(91,124,253,0.12)',
  white: '#fff',
  black: '#111111',
  darkGray: '#232522',
  lightGray: '#F9F9F9',
  mediumGray: '#D9D9D9',
  gray: '#828282',
  dividerLight: 'rgba(0,0,0,0.12)',
  dividerDark: 'rgba(255,255,255,0.12)',
  green: '#43A047',
  red: '#ff0000',
  transparentBlack: 'rgba(0,0,0,0.5)',
};

// colors
export const colors = {
  light: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      ...commonColors,
      primary: commonColors.lightGray,
      background: commonColors.lightGray,
      text: commonColors.darkGray,
      dividerColor: commonColors.dividerLight,
      splashTheme: {
        mainBackgroundColor: commonColors.brandColor,
        appName: commonColors.white,
        tagLine: commonColors.white,
      },
      loginSignupTheme: {
        mainBackgroundColor: commonColors.brandColor,
        marqueeItemBackgroundColor: commonColors.white,
        marqueeItemTextColor: commonColors.darkGray,
        loginSignupContainerBackgroundColor: commonColors.white,
        loginSignupSubText: commonColors.darkGray,
        termsTextColor: commonColors.darkGray,
        conditionTextColor: commonColors.darkGray,
      },
      loginSignupModalTheme: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
        descriptionColor: commonColors.gray,
        containerBackgroundColor: commonColors.lightGray,
      },
      otpVerificationTheme: {
        mainBackgroundColor: commonColors.brandColor,
        otpVerificationContainerBackgroundColor: commonColors.white,
        resendOtpTextColor: commonColors.darkGray,
      },
      profileInfoTheme: {
        mainBackgroundColor: commonColors.brandColor,
        profileInfoContainerBackgroundColor: commonColors.white,
        contactDetailsTextColor: commonColors.darkGray,
      },
      selectPreferencesTheme: {
        mainBackgroundColor: commonColors.brandColor,
        selectPrefContainerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        itemBackgroundColor: commonColors.lightGray,
      },
      preferencesTheme: {
        mainBackgroundColor: commonColors.lightGray,
        selectPrefContainerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        itemBackgroundColor: commonColors.lightGray,
      },
      profileTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        editButtonBackgroundColor: commonColors.white,
      },
      buttonTheme: {
        primaryTextColor: commonColors.white,
        disabledButtonBackgroundColor: commonColors.brandColorLight,
        linkIconColor: commonColors.white,
        linkTextColor: commonColors.white,
        activityIndicatorColor: commonColors.white,
      },
      inputTheme: {
        textInputContainerBackgroundColor: commonColors.lightGray,
        textInputColor: commonColors.darkGray,
        textInputContainerBorderColor: commonColors.dividerLight,
      },
      headerTheme: {
        leftTextColor: commonColors.darkGray,
        notificationIconBackgroundColor: commonColors.white,
        notificationIconTintColor: commonColors.darkGray,
      },
      termsAndConditionsTheme: {
        containerBackgroundColor: commonColors.white,
        level0TextColor: commonColors.darkGray,
      },
      notificationSettingsTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
      },
      accountSettingsTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
      },
      aboutUsTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
      },
      privacyPolicyTheme: {
        containerBackgroundColor: commonColors.white,
        level0TextColor: commonColors.darkGray,
      },
      writeReviewTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        dividerColor: commonColors.dividerLight,
      },
      shareFeedbackTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        dividerColor: commonColors.dividerLight,
      },
      helpCenterTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        color: commonColors.darkGray,
        dividerColor: commonColors.dividerLight,
      },
      otpInputTheme: {
        backgroundColor: commonColors.black,
        borderColor: commonColors.dividerLight,
        color: commonColors.darkGray,
      },
      toastTheme: {
        backgroundColor: commonColors.brandColor,
        color: commonColors.white,
        shadowColor: commonColors.darkGray,
      },
      toggleSwitchTheme: {
        thumbColor: commonColors.lightGray,
        inactiveColor: commonColors.mediumGray,
        activeColor: commonColors.brandColor,
      },
      tabBarTheme: {
        dividerColor: 'rgba(35,37,34,0.12)',
        color: commonColors.white,
      },
      mallsTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.darkGray,
        backgroundColor: commonColors.lightGray,
        buttonBackgroundColor: commonColors.white,
      },
      allInCityTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.darkGray,
        backgroundColor: commonColors.lightGray,
        buttonBackgroundColor: commonColors.white,
        menuTitle: commonColors.white,
        tabBackgroundColor: commonColors.lightGray,
      },
      hubsTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.darkGray,
        backgroundColor: commonColors.lightGray,
        buttonBackgroundColor: commonColors.white,
      },
      homeTheme: {
        notEverywhereYettColor: commonColors.black,
        locationBackgroundColor: commonColors.white,
        cityItem: commonColors.white,
        cityName: commonColors.black,
        arrow: commonColors.black,
      },
      inboxTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        itemBackgroundColor: commonColors.lightGray,
        discretionColor: commonColors.black,
      },
      notificationTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        itemBackgroundColor: commonColors.lightGray,
        discretionColor: commonColors.black,
        nothingYettColor: commonColors.black,
      },
      receiptsTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        itemBackgroundColor: commonColors.lightGray,
        titleColor: commonColors.black,
        amountColor: commonColors.black,
        nothingYettColor: commonColors.black,
      },
      editProfileModalTheme: {
        backgroundColor: commonColors.white,
        iconBackgroundColor: ' rgba(91, 124, 253, 0.08)',
        deleteIconBackgroundColor: ' rgba(255, 0, 0, 0.08)',
        closeIconTintColor: commonColors.white,
        titleColor: commonColors.black,
        input: commonColors.lightGray,
      },
      editProfileDetailsModalTheme: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
      },
      verifyOTPModalTheme: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
        weHaveSentColor: 'rgba(0,0,0,0.48)',
        phoneNumberColor: commonColors.black,
      },
      addProductAlertModalTheme: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
      },
      favouritesTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.darkGray,
        backgroundColor: commonColors.lightGray,
        buttonBackgroundColor: commonColors.white,
      },
      upcomingEventTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        cardBackgroundColor: commonColors.lightGray,
        eventTitleColor: commonColors.black,
        addressColor: commonColors.black,
        capacityColor: commonColors.black,
      },
      productsTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        productTitleColor: commonColors.black,
        categoryImageBackgroundColor: commonColors.white,
        productBorderColor: commonColors.mediumGray,
      },
      storesTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        storeNameColor: commonColors.black,
        storeAddressColor: commonColors.black,
      },
      brandAndMallDetails: {
        mainBackgroundColor: commonColors.white,
        titleColor: commonColors.black,
        timeColor: commonColors.black,
        categoryColor: commonColors.black,
        postDescription: commonColors.black,
        serviceContainer: commonColors.lightGray,
        toolsBackgroundColor: commonColors.white,
        reviewContainer: commonColors.lightGray,
        reviewerName: commonColors.black,
        reviewDiscretion: commonColors.black,
        amenitiesContainer: commonColors.lightGray,
        amenitiesIconBackgroundColor: commonColors.white,
      },
      productAlertSuccessModalTheme: {
        backgroundColor: commonColors.white,
        productDetailsBackgroundColor: commonColors.lightGray,
      },
      chatTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        brandChatContainer: commonColors.lightGray,
        userChatContainer: 'rgba(91,124,253,0.08)',
      },
      popupModalTheme: {
        mainBackgroundColor: commonColors.white,
      },
      conversationTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        itemBackgroundColor: commonColors.lightGray,
        discretionColor: commonColors.black,
      },
      bottomBarTheme: {
        backgroundColor: commonColors.lightGray,
        color: commonColors.black,
      },
      genderModalTheme: {
        backgroundColor: 'rgba(91, 124, 253, 0.08)',
      },
      searchTheme: {
        mainBackgroundColor: commonColors.lightGray,
        containerBackgroundColor: commonColors.white,
        highlightText: commonColors.black,
        input: commonColors.white,
      },
      loader: {
        loaderContainer: commonColors.brandColor,
        dotColor: commonColors.white,
      },
      loadMore: {
        activityIndicatorColor: commonColors.brandColor,
        color: commonColors.brandColor,
      },
      productModal: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
        name: commonColors.black,
        description: commonColors.gray,
        price: commonColors.brandColor,
        dot: commonColors.black,
      },
      offerModal: {
        backgroundColor: commonColors.white,
        titleColor: commonColors.black,
        name: commonColors.black,
        description: commonColors.gray,
      },
    },
  },
  dark: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      ...commonColors,
      primary: commonColors.black,
      background: commonColors.black,
      text: commonColors.white,
      dividerColor: commonColors.dividerDark,
      splashTheme: {
        mainBackgroundColor: commonColors.black,
        appName: commonColors.brandColor,
        tagLine: commonColors.white,
      },
      loginSignupTheme: {
        mainBackgroundColor: commonColors.black,
        marqueeItemBackgroundColor: commonColors.darkGray,
        marqueeItemTextColor: commonColors.white,
        loginSignupContainerBackgroundColor: commonColors.darkGray,
        loginSignupSubText: commonColors.white,
        termsTextColor: commonColors.white,
        conditionTextColor: commonColors.white,
      },
      loginSignupModalTheme: {
        backgroundColor: commonColors.black,
        titleColor: commonColors.white,
        descriptionColor: commonColors.gray,
        containerBackgroundColor: commonColors.darkGray,
      },
      otpVerificationTheme: {
        mainBackgroundColor: commonColors.black,
        otpVerificationContainerBackgroundColor: commonColors.darkGray,
        resendOtpTextColor: commonColors.white,
      },
      profileInfoTheme: {
        mainBackgroundColor: commonColors.black,
        profileInfoContainerBackgroundColor: commonColors.darkGray,
        contactDetailsTextColor: commonColors.white,
      },
      selectPreferencesTheme: {
        mainBackgroundColor: commonColors.black,
        selectPrefContainerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        itemBackgroundColor: commonColors.black,
      },
      preferencesTheme: {
        mainBackgroundColor: commonColors.black,
        selectPrefContainerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        itemBackgroundColor: commonColors.black,
      },
      profileTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        editButtonBackgroundColor: commonColors.darkGray,
      },
      buttonTheme: {
        primaryTextColor: commonColors.darkGray,
        disabledButtonBackgroundColor: commonColors.brandColorLight,
        linkIconColor: commonColors.darkGray,
        linkTextColor: commonColors.darkGray,
        activityIndicatorColor: commonColors.darkGray,
      },
      inputTheme: {
        textInputContainerBackgroundColor: commonColors.black,
        textInputColor: commonColors.white,
        textInputContainerBorderColor: commonColors.dividerDark,
      },
      headerTheme: {
        leftTextColor: commonColors.white,
        notificationIconBackgroundColor: commonColors.darkGray,
        notificationIconTintColor: commonColors.white,
      },
      termsAndConditionsTheme: {
        containerBackgroundColor: commonColors.darkGray,
        level0TextColor: commonColors.white,
      },
      notificationSettingsTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
      },
      accountSettingsTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
      },
      aboutUsTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
      },
      privacyPolicyTheme: {
        containerBackgroundColor: commonColors.darkGray,
        level0TextColor: commonColors.white,
      },
      writeReviewTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        dividerColor: commonColors.dividerDark,
      },
      shareFeedbackTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        dividerColor: commonColors.dividerDark,
      },
      helpCenterTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        color: commonColors.white,
        dividerColor: commonColors.dividerDark,
      },
      otpInputTheme: {
        backgroundColor: commonColors.black,
        borderColor: commonColors.dividerDark,
        color: commonColors.white,
      },
      toastTheme: {
        backgroundColor: commonColors.darkGray,
        color: commonColors.brandColor,
        shadowColor: commonColors.white,
      },
      toggleSwitchTheme: {
        thumbColor: commonColors.black,
        inactiveColor: commonColors.gray,
        activeColor: commonColors.brandColor,
      },
      tabBarTheme: {
        dividerColor: commonColors.dividerDark,
        color: commonColors.darkGray,
      },
      mallsTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.white,
        backgroundColor: commonColors.black,
        buttonBackgroundColor: commonColors.darkGray,
      },
      allInCityTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.white,
        backgroundColor: commonColors.black,
        buttonBackgroundColor: commonColors.darkGray,
        menuTitle: commonColors.black,
        tabBackgroundColor: commonColors.black,
      },
      hubsTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.white,
        backgroundColor: commonColors.black,
        buttonBackgroundColor: commonColors.darkGray,
      },
      homeTheme: {
        notEverywhereYettColor: commonColors.white,
        locationBackgroundColor: commonColors.darkGray,
        cityItem: commonColors.darkGray,
        cityName: commonColors.white,
        arrow: commonColors.gray,
      },
      inboxTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        itemBackgroundColor: commonColors.black,
        discretionColor: commonColors.white,
      },
      notificationTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        itemBackgroundColor: commonColors.black,
        discretionColor: commonColors.white,
        nothingYettColor: commonColors.white,
      },
      receiptsTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        itemBackgroundColor: commonColors.black,
        titleColor: commonColors.white,
        amountColor: commonColors.white,
        nothingYettColor: commonColors.white,
      },
      editProfileModalTheme: {
        backgroundColor: commonColors.darkGray,
        iconBackgroundColor: ' rgba(91, 124, 253, 0.08)',
        deleteIconBackgroundColor: ' rgba(255, 0, 0, 0.08)',
        closeIconTintColor: commonColors.white,
        titleColor: commonColors.white,
        input: commonColors.black,
      },
      editProfileDetailsModalTheme: {
        backgroundColor: commonColors.black,
        titleColor: commonColors.white,
      },
      verifyOTPModalTheme: {
        backgroundColor: commonColors.black,
        weHaveSentColor: 'rgba(255,255,255,0.48)',
        phoneNumberColor: commonColors.white,
      },
      addProductAlertModalTheme: {
        backgroundColor: commonColors.black,
        titleColor: commonColors.white,
      },
      favouritesTheme: {
        dividerColor: 'rgba(35,37,34,0.08)',
        color: commonColors.white,
        backgroundColor: commonColors.black,
        buttonBackgroundColor: commonColors.darkGray,
      },
      upcomingEventTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        cardBackgroundColor: commonColors.black,
        eventTitleColor: commonColors.white,
        addressColor: commonColors.white,
        capacityColor: commonColors.white,
      },
      productsTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        productTitleColor: commonColors.white,
        categoryImageBackgroundColor: commonColors.black,
        productBorderColor: commonColors.black,
      },
      storesTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        storeNameColor: commonColors.white,
        storeAddressColor: commonColors.white,
      },
      brandAndMallDetails: {
        mainBackgroundColor: commonColors.darkGray,
        titleColor: commonColors.white,
        timeColor: commonColors.white,
        categoryColor: commonColors.white,
        postDescription: commonColors.white,
        serviceContainer: commonColors.black,
        toolsBackgroundColor: commonColors.darkGray,
        reviewContainer: commonColors.black,
        reviewerName: commonColors.white,
        reviewDiscretion: commonColors.white,
        amenitiesContainer: commonColors.black,
        amenitiesIconBackgroundColor: commonColors.darkGray,
      },
      productAlertSuccessModalTheme: {
        backgroundColor: commonColors.black,
        productDetailsBackgroundColor: commonColors.darkGray,
      },
      chatTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        brandChatContainer: commonColors.black,
        userChatContainer: 'rgba(91,124,253,0.12)',
      },
      popupModalTheme: {
        mainBackgroundColor: commonColors.black,
      },
      conversationTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        itemBackgroundColor: commonColors.black,
        discretionColor: commonColors.white,
      },
      bottomBarTheme: {
        backgroundColor: commonColors.black,
        color: commonColors.white,
      },
      genderModalTheme: {
        backgroundColor: 'rgba(91, 124, 253, 0.5)',
      },
      searchTheme: {
        mainBackgroundColor: commonColors.black,
        containerBackgroundColor: commonColors.darkGray,
        highlightText: commonColors.white,
        input: commonColors.darkGray,
      },
      loader: {
        loaderContainer: commonColors.brandColor,
        dotColor: commonColors.black,
      },
      loadMore: {
        activityIndicatorColor: commonColors.brandColor,
        color: commonColors.brandColor,
      },
      productModal: {
        backgroundColor: commonColors.black,
        titleColor: commonColors.white,
        name: commonColors.white,
        description: commonColors.gray,
        price: commonColors.brandColor,
        dot: commonColors.white,
      },
      offerModal: {
        backgroundColor: commonColors.black,
        titleColor: commonColors.white,
        name: commonColors.white,
        description: commonColors.gray,
      },
    },
  },
};
